book/urls.py
from django.urls import path

from book.views import RegisterView, LoginView, MyBookView, BookshelfCreateView, LogoutView, UserProfileView, \
    UserUpdateProfileView

app_name = "book"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("edit-profile/", UserUpdateProfileView.as_view(), name="update-profile"),
    path("my_book/", MyBookView.as_view(), name="my-book"),
    path("new-bookshelf/", BookshelfCreateView.as_view(), name="new-bookshelf"),
]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('book/', include("book.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.contrib.auth import password_validation
from django.contrib.auth.models import AbstractUser, User, Group, Permission
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Users(AbstractUser):
    middle_name = models.CharField(max_length=56, null=True, blank=True)
    avatar = models.ImageField(upload_to="avatar/", null=True, blank=True)


class Book(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=128)
    published = models.DateField()
    isbn = models.CharField(max_length=128, unique=True)
    language = models.CharField(max_length=12, blank=True, null=True)
    page = models.IntegerField()
    authors = models.ManyToManyField("Author")
    genres = models.ManyToManyField("Genre", "books")
    cover = models.ImageField(upload_to="book_cover/")

    def __str__(self):
        return self.title


class Bookshelf(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(Users, models.CASCADE, "shelfs")
    books = models.ManyToManyField(Book, "shelfs")


class BookReview(models.Model):
    body = models.TextField()
    book = models.ForeignKey(Book, models.CASCADE, "reviws")
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    owner = models.ForeignKey(Users, models.CASCADE, "reviews")
    like_count = models.IntegerField(default=0)


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    website = models.URLField(max_length=128, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    avatar = models.ImageField(upload_to="author_avatar/", default="avatar.jpg")
    genre = models.ForeignKey("Genre", models.SET_NULL, null=True)


class Genre(models.Model):
    name = models.CharField(max_length=28)


class BlockedUsers(models.Model):
    name = models.CharField(max_length=28)
    address = models.CharField(max_length=28)

    def __str__(self):
        return self.name

book/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from book.models import Users, Bookshelf


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    # def clean_password(self):
    #     password = self.cleaned_data.get("password")
    #     if password:
    #         try:
    #             password_validation.validate_password(password, self.instance)
    #         except ValidationError as error:
    #             self.add_error("password", error)
    #     return password

    class Meta:
        model = Users
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "middle_name",
            "avatar",
            "password",
            "confirm_password"
        )

    def clean_username(self):
        username = self.cleaned_data["username"]
        if Users.objects.filter(username=username).exists():
            msg = 'this username already taken please choose another one'
            self.add_error('username', msg)
        return username

    def clean(self):
        if self.cleaned_data["password"] != self.cleaned_data["confirm_password"]:
            msg = "password and confirm_password must be match"
            self.add_error("confirm_password", msg)

        return self.cleaned_data

    def save(self):
        user = Users.objects.create(
            username=self.cleaned_data["username"],
            email=self.cleaned_data["email"],
            middle_name=self.cleaned_data["middle_name"],
            first_name=self.cleaned_data["first_name"],
            last_name=self.cleaned_data["last_name"],
            avatar=self.cleaned_data["avatar"],
        )
        user.set_password(self.cleaned_data["password"])
        user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_password(self):
        try:
            user = Users.objects.get(username=self.cleaned_data.get("username"))
            # if not user.check_password(raw_password=value):
            #     user.login_try_count=+1
            # else:
            #     user.login_try_count=0
            # user.save()
            #
        except Users.DoesNotExist:
            return self.cleaned_data.get("password")
        return self.cleaned_data.get("password")


class BookshelfForm(forms.ModelForm):
    class Meta:
        model = Bookshelf
        fields = "__all__"


class UserUpdateForm(ModelForm):
    class Meta:
        model = Users
        fields = ("first_name", "last_name", "middle_name", "email", "avatar", "username",)

book/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView

from book.forms import RegisterForm, LoginForm, BookshelfForm, UserUpdateForm
from book.models import Users, Book, Bookshelf


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        context = {
            "form": form
        }
        return render(request, "book/register.html", context=context)

    def post(self, request):
        form = RegisterForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            Bookshelf.objects.create(owner=user, name="Read")
            Bookshelf.objects.create(owner=user, name="Currently Reading")
            Bookshelf.objects.create(owner=user, name="Want To Read")
            return redirect("book:login")
        else:
            context = {
                "form": form
            }
            return render(request, "book/register.html", context=context)


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        context = {
            "form": form
        }
        return render(request, "book/login.html", context=context)

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data["username"], password=form.cleaned_data["password"])
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {user.username}.")
                return redirect("home")
            else:
                messages.warning(request, "With given data user not found")
                return redirect("home")


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect("home")


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request):
        context = {
            "user": request.user
        }
        return render(request, "book/profile.html", context=context)


class UserUpdateProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user = get_object_or_404(Users, username=request.user.username)
        form = UserUpdateForm(instance=user)
        context = {
            "form": form
        }
        return render(request, "book/user-profile-update.html", context=context)

    def post(self, request):
        form = UserUpdateForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "User profile successfuly updated")
            return redirect("book:profile")
        else:
            context = {
                "form": form
            }
            return render(request, "book/user-profile-update.html", context=context)


class MyBookView(View, LoginRequiredMixin):
    def get(self, request):
        shelves = Bookshelf.objects.filter(owner=request.user)
        context = {
            "shelves": shelves
        }
        return render(request, "book/my_book.html", context=context)


class BookshelfCreateView(CreateView, LoginRequiredMixin):
    queryset = Bookshelf.objects.all()
    template_name = "book/new-bookshelf.html"
    form_class = BookshelfForm
    success_url = reverse_lazy("book:my-book")

templates/book/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}

    <h3>Login Page</h3>
    <form action="{% url 'book:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <p>Do you not have account? Than <a href="{% url 'book:register' %}">register</a></p>
        <button type="submit"> Login</button>
    </form>


{% endblock %}

templates/book/my_book.html
{% extends 'base.html' %}
{% block title %} My Books {% endblock %}
{% block content %}
    {% include 'category.html' %}

    {% for shelf in shelves %}
        <ul type="none">
            <li>{{ shelf.name }}</li>
            <ol>
                {% for book in shelf.books.all %}
                    <li> {{ book.title }}</li>
                {% endfor %}
            </ol>

        </ul>
    {% endfor %}
{% endblock %}

templates/book/new-bookshelf.html
{% extends 'base.html' %}
{% block content %}
    {% include 'category.html' %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/book/profile.html
{% extends 'base.html' %}
{% block content %}
    {% include 'category.html' %}
    <div class="row " style="display: flex; justify-content: center; text-align: center">

        <img src="{{user.avatar.url }}" class="rounded-circle mb-3" style="width: 150px;"
             alt="Avatar"/>

        <h5 class="mb-2"><strong>{{ user.first_name }} {{ user.last_name }}</strong></h5>
        <h6 class="mb-2"><strong>{{ user.email}}</strong></h6>
        <p class="text-muted"> <span class="badge bg-primary">{{ user.username }}</span></p>
        <a href="{% url 'book:update-profile' %}">Edit</a>

    </div>



{% endblock %}

templates/book/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
    <h3>Register Page</h3>
    <form action="{% url 'book:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>Do you have already account? Than <a href="{% url 'book:login' %}">log in</a></p>
        <button type="submit"> Register</button>
    </form>


{% endblock %}

templates/book/user-profile-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}#


{% block content %}
    {% include 'category.html' %}
    <div class="row">
        <div class="col-6">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}`
                <button type="submit" class="btn btn-primary">Update</button>
            </form>

        </div>

    </div>

{% endblock %}