book/urls.py
from django.urls import path

from book.views import RegisterView, LoginView, MyBookView, BookshelfCreateView, LogoutView, UserProfileView, \
    UserUpdateProfileView

app_name = "book"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("edit-profile/", UserUpdateProfileView.as_view(), name="update-profile"),
    path("my_book/", MyBookView.as_view(), name="my-book"),
    path("new-bookshelf/", BookshelfCreateView.as_view(), name="new-bookshelf"),
]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('book/', include("book.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container">
    
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
        <strong>Message: </strong> {{ message }}
    </div>
{% endfor %}

{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</div>

</body>
</html>

templates/category.html
{% if request.user.is_authenticated %}
    <a href="{% url 'book:my-book' %}">My Books</a>
    <a href="{% url 'book:new-bookshelf' %}">New Bookshelf</a>
{% else %}
    <a href="{% url 'book:register' %}">Register</a>
    <a href="{% url 'book:login' %}">Login</a>
{% endif %}
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" type="None">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <li type="None" class="nav-item dropdown">
                {% if not request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'book:login' %}">
                        Login
                    </a>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Profile
                    </a>
                    <ul class="dropdown-menu" type="None">
                        <li><a class="dropdown-item" href="{% url 'book:profile' %}">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'book:logout' %}">Logut</a></li>
                    </ul>
                    </li>
                {% endif %}
        </div>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}

{% block content %}
    {% include 'category.html' %}
{% endblock %}